apiVersion: v1
kind: Service
metadata:
  name: icrmservice
  labels:
    app: backend
spec:
  type: NodePort
  ports:
    -  nodePort: 30001
       port: 80
       targetPort: 80
  selector:
    type: myapp
    app: backend

